---



- name: Include the variables specific to the vpc
  include_vars: envs/{{ environ| default("dev.yaml") }}
- name: be sure exists 2 public 2 private subnets in vpc
  local_action:
    module: ec2_vpc
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: { "Environment":"Development" }
    region: ap-northeast-1
    subnets: "{{ vpc_subnets }}"
    internet_gateway: "{{ vpc_internet_gateway|string }}"
    route_tables: "{{ vpc_route_tables }}"
  register: vpc
- debug: var=vpc
