---
- name: Include the variables specific to the vpc
  include_vars: envs/{{ environ| default("dev.yaml") }}
- name: be sure exists 2 public 2 private subnets in vpc
  local_action:
    module: ec2_vpc
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: { "Environment":"Development", "Name":"ansibleVpc" }
    region: ap-northeast-1
    subnets: "{{ vpc_subnets }}"
    internet_gateway: "{{ vpc_internet_gateway|string }}"
    route_tables: "{{ vpc_route_tables }}"
  register: vpc
- name: Write temp file for creating subnet map
  template: src=subnet_id.j2 dest=/tmp/subnet_id
- name: Create subnet map
  set_fact:
    subnet_map: "{{ lookup('file', '/tmp/subnet_id') }}"
- debug: var=vpc
- debug: var=subnet_map
