subnets_hash:
    name: dev
vpc_cidr_block: 10.0.0.0/16
vpc_subnets:
    - cidr: 10.0.1.0/24
      az: ap-northeast-1a
      resource_tags: { "Name":"PublicA"}
    - cidr: 10.0.2.0/24
      az: ap-northeast-1c
      resource_tags: { "Name":"PublicC"}
    - cidr: 10.0.3.0/24
      az: ap-northeast-1a
      resource_tags: { "Name":"PrivateA"}
    - cidr: 10.0.4.0/24
      az: ap-northeast-1c
      resource_tags: { "Name":"PrivateC"}
vpc_internet_gateway: "yes"
vpc_route_tables:
    - subnets:
        - 10.0.1.0/24
        - 10.0.2.0/24
      routes:
        - dest: 0.0.0.0/0
          gw: igw
    - subnets:
        - 10.0.3.0/24
        - 10.0.4.0/24
      routes:
        - dest: 0.0.0.0/0
          gw: igw
vpc_public_subnet: 
    - 10.0.1.0/24
    - 10.0.2.0/24
vpc_nat_instance_id: ami-4f9fee26 
vpc_nat_instance_type: t1.micro
vpc_group:
    name: dev_vpc
    desc: the security group for the dev vpc
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

vpc_instances:
  - instance_type: m1.medium
    image: 
    keypair: 
    group: dev_vpc
    instance_tags: 
        Name: dev_db
   # exact_count: 2
   # count_tag: 
   #     Name: dev_db_count
    subnet: 10.0.3.0/24

  - instance_type: m1.medium
    image: 
    keypair: 
    group: dev_vpc
    instance_tags: 
        Name: dev_app
   # exact_count: 2
   # count_tag: 
   #     Name: dev_app_count
    subnet: 10.0.2.0/24

  - instance_type: m1.medium
    image: 
    keypair: 
    group: dev_proxy
    instance_tags: 
        Name: dev_proxy
   # exact_count: 2
   # count_tag: 
   #     Name: dev_proxy_count
    subnet: 10.0.1.0/24