subnets_hash:
    name: dev
vpc_cidr_block: 10.0.0.0/16
vpc_subnets:
    - cidr: 10.0.1.0/24
      az: ap-northeast-1a
      resource_tags: { "Name":"PublicA"}
    - cidr: 10.0.2.0/24
      az: ap-northeast-1c
      resource_tags: { "Name":"PublicC"}
    - cidr: 10.0.3.0/24
      az: ap-northeast-1a
      resource_tags: { "Name":"PrivateA"}
    - cidr: 10.0.4.0/24
      az: ap-northeast-1c
      resource_tags: { "Name":"PrivateC"}
vpc_internet_gateway: "yes"
vpc_route_tables:
    - subnets:
        - 10.0.1.0/24
        - 10.0.2.0/24
      routes:
        - dest: 0.0.0.0/0
          gw: igw
    - subnets:
        - 10.0.3.0/24
        - 10.0.4.0/24
      routes:
        - dest: 0.0.0.0/0
          gw: igw
vpc_public_subnet: 
    - 10.0.1.0/24
    - 10.0.2.0/24
